# Hyperband Settings
HYPERBAND_OBJECTIVE = 'val_accuracy'
HYPERBAND_MAX_EPOCHS = 10
HYPERBAND_FACTOR = 3
HYPERBAND_ITERATIONS = 3

HYPERBAND_TRAININGS_EPOCHS = 150
HYPERBAND_TUNER_EPOCHS = 150
HYPERBAND_TUNER_VALIDATION_SPLIT = 0.2

# Classifier CNN Settings
CNN_FILTERS_LAYER_1 = 64
CNN_KERNELS_LAYER_1 = 3

CNN_FIRST_LAYERS_LOWER_LIMIT = 0
CNN_FIRST_LAYERS_UPPER_LIMIT = 6

CNN_FIRST_LAYERS_FILTERS_CHOICE_VALUES = [32, 64, 128, 256, 512]
CNN_FIRST_LAYERS_FILTERS_CHOICE_DEFAULT = 64
CNN_FIRST_LAYERS_KERNEL_SIZE = 3

#TODO: Generator scripte anpassen
CNN_POOLING_LAYER = 'max_polling_layer'
CNN_POOLING_SIZE = 2
CNN_POOLING_STRIDES = 2

CNN_SECOND_LAYERS_LOWER_LIMIT = 1
CNN_SECOND_LAYERS_UPPER_LIMIT = 3

CNN_SECOND_LAYERS_UNITS_CHOICE_MIN = 32
CNN_SECOND_LAYERS_UNITS_CHOICE_MAX = 512
CNN_SECOND_LAYERS_UNITS_CHOICE_STEP = 32

CNN_ACTIVATION_FUNCTIONS_VALUES = ['relu']
CNN_ACTIVATION_FUNCTIONS_DEFAULT = 'relu'

CNN_LEARNING_RATE_CHOICE = [1e-2, 1e-3, 1e-4, 1e-5]
CNN_LOSS_FUNCTION = 'sparse_categorical_crossentropy'

# Classifier CNN+LSTM Settings
CNN_LSTM_FILTERS_LAYER_1 = 64
CNN_LSTM_KERNELS_LAYER_1 = 3

CNN_LSTM_FIRST_LAYERS_LOWER_LIMIT = 0
CNN_LSTM_FIRST_LAYERS_UPPER_LIMIT = 5

CNN_LSTM_FIRST_LAYERS_FILTERS_CHOICE_VALUES = [32, 64, 128, 256, 512]
CNN_LSTM_FIRST_LAYERS_FILTERS_CHOICE_DEFAULT = 64
CNN_LSTM_FIRST_LAYERS_KERNEL_SIZE = 3

#TODO: Generator scripte anpassen
CNN_LSTM_POOLING_LAYER = 'max_polling_layer'
CNN_LSTM_POOLING_SIZE = 2
CNN_LSTM_POOLING_STRIDES = 2

CNN_LSTM_SECOND_LAYERS_LOWER_LIMIT = 1
CNN_LSTM_SECOND_LAYERS_UPPER_LIMIT = 5

CNN_LSTM_SECOND_LAYERS_UNITS_CHOICE_MIN = 23
CNN_LSTM_SECOND_LAYERS_UNITS_CHOICE_MAX = 512
CNN_LSTM_SECOND_LAYERS_UNITS_CHOICE_STEP = 32

CNN_LSTM_ACTIVATION_FUNCTIONS_VALUES = ['relu']
CNN_LSTM_ACTIVATION_FUNCTIONS_DEFAULT = 'relu'

CNN_LSTM_LEARNING_RATE_CHOICE = [1e-2, 1e-3, 1e-4, 1e-5]
CNN_LSTM_LOSS_FUNCTION = 'sparse_categorical_crossentropy'


# Conditional Wasserstein GAN Settings
CW_GAN_TRAININGS_EPOCHS = 1

# -Generator
GENERATOR_FILTERS_LAYER_1 = 128
GENERATOR_FILTERS_LAYER_2 = 64

GENERATOR_LEARNING_RATE = 0.0002
GENERATOR_BETA_1 = 0.5
GENERATOR_BETA_2 = 0.9

# -Discriminator
DISCRIMINATOR_FILTERS_LAYER_1 = 64
DISCRIMINATOR_FILTERS_LAYER_2 = 128
DISCRIMINATOR_FILTERS_LAYER_3 = 256
DISCRIMINATOR_FILTERS_LAYER_4 = 512

DISCRIMINATOR_LEARNING_RATE = 0.0002
DISCRIMINATOR_BETA_1 = 0.5
DISCRIMINATOR_BETA_2 = 0.9

DISCRIMINATOR_EXTRA_STEPS = 3
